########################################################
# Aegis Filter – SonarCloud Configuration
# Curso: SI784 – Calidad y Pruebas de Software
########################################################

sonar.projectKey=aegisfilter-techhub
sonar.projectName=Aegis Filter
sonar.projectVersion=1.0.0

# Código fuente a analizar
sonar.sources=app,routes,database
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Exclusiones del análisis
sonar.exclusions=\
    vendor/**,\
    node_modules/**,\
    storage/**,\
    bootstrap/cache/**,\
    *.blade.php

# Reportes de cobertura (generados por PHPUnit + Xdebug)
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=test-report.xml

# Quality Gate
sonar.qualitygate.wait=true
